name: Build and Deploy React app from main to GitHub Pages gh-pages branch

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run : cat .git/config
    - run : git config user.name github-actions
      shell: bash
    - run : git config user.email github-actions@github.com
      shell: bash
    - run : git worktree add -b gh-pages build origin/gh-pages
      shell: bash
    - run : cp -r dist/* build/
      shell: bash
    - run : git add --all
      working-directory: ./build
      shell: bash
    - run : git commit --allow-empty -m "Automatic Build and Deploy run by GitHub Actions of commit ${{ github.sha }}."
      working-directory: ./build
      shell: bash
    - run : git push
      working-directory: ./build
      shell: bash
